#!/bin/bash

mkdir -p Modules/Plugin Doc/remapt

nmake clean
nmake all

cp remapt.dll Modules/Plugin
cp README COPYING keymap-default.cfg Doc/remapt

# convert line endings to DOS format
sed -ri 's/(^|[^\r])$/&\r/' Doc/remapt/*

zip -r remapt.zip Modules Doc

nmake clean
rm -r Modules Doc
